### ISSUE TITLE
Filter by Collection -> 'Latest' is twice in the list.

### ISSUE THREAD

**Issue by unholyeyebrows** [baconpaul/airwin2rack#171]
Hi

On Windows x64, I am seeing the 'Latest' option shown twice in the 'Filter by Collection' menu. I have uninstalled and re-installed but this has not solved it.

Prob,em seen in stand-alone app as well as the VST and CLAP plugins. See attached screenshot.

Thanks
Nick
![Screenshot 2024-12-10 134015](https://github.com/user-attachments/assets/d37ca4d2-a0f9-4afd-85d1-697a17e31740)

**Comment by baconpaul** [comment]
Thanks 

my guess is @airwindows has a trailing space in the pedia somewhere and my parser is not stripping it. I’ll take a peek after the weekend

**Comment by airwindows** [comment]
I think I found it. You can adjust your parser if you like but I adjusted what.txt so it will probably go away again…

Cans used [Latest,Recommended] but everything else was in the form of [Recommended,Latest]. I think that must be what did it: your parser assumed things would be in an expected order, and an instance came in where the order was reversed, which seems to have forced it into a distinct category? At least, that's what I observed, and it's a recent 'bug'. If you like, see if the parser is sensitive to the order of the categories as read, because that was a departure from all other instances of 'Latest', and it was only order, not a trailing space.

**Comment by baconpaul** [comment]
ahh ok well it will get fixed on Sunday then, but lets leave this open and I can figure out why the parser failed there. It really shouldn't. Do you have the commit where you fix the pedia so i can backtrack and adjust one day?

**Comment by baconpaul** [comment]
and thanks!
