### ISSUE TITLE
DAW automation lanes display

### ISSUE THREAD

**Issue by mahlonsmith** [baconpaul/airwin2rack#83]
In the LV2, the automation lane options appear to be stuck on the initial "Galactic" setting.

This only appears to be a problem with the display, as the automation itself still works -- just need to visually line up which "knob" you're on.  :-)

![screenshot-1715053528](https://github.com/baconpaul/airwin2rack/assets/3220479/428f83f5-28c3-443e-8bb8-551b36db6a0f)

**Comment by baconpaul** [comment]
The vst3 clap and au do the right thing in the hosts I’ve tried. Can you try any of those formats? I think ardour supports vst3 yeah?

if so I can flag this as a problem with juce and maybe they can fix it

**Comment by baconpaul** [comment]
Oh right LV2 has that weird thing where it puts the parameter names in the ttl file at build time.

I wonder if LV2 just can't handle engine morphing track names.

This implementation in the JUCE LV2 wrapper

```
 void audioProcessorChanged (AudioProcessor*, const ChangeDetails&) override {}
```

is very different than the VST3 and CLAP ones though. So I think this is either a JUCE shortcoming or an LV2 format shortcoming.

Curious if the VST3 does the right thing in Ardour?

**Comment by mahlonsmith** [comment]
Ah, yep!  VST3 version works as expected.  :+1:   I'll chalk that up to LV2 limitations and go that route.

**Comment by baconpaul** [comment]
You may want to let the ardour team know. If they can tell you what to put inside that block perhaps the Juce team would be interested! It may not be an LV2 limitation as much as a JUCE implementation of LV2 incompleteness. But it might be an LV2 limitation!

(I have no idea how LV2 works really so wouldn't know where to start).

I'm going to close this since there's nothing *I* can change to fix it. But feel free to point folks here if they have ideas.
