### ISSUE TITLE
Level / input/output control for Airwindows Consolidated

### ISSUE THREAD

**Issue by redactedscribe** [baconpaul/airwin2rack#85]
Hello,

Would it be possible for a basic global level or output control to be added to the interface? This would mean we could gain-stage within the plugin and more easily A-B the results (rather than having to disable it and some additional gain plugin/device). It's quite easy to create a chain in some DAWs like Ableton Live and Bitwig Studio and toggle the chain instead, but it seems like that shouldn't be necessary and is something that this consolidated plugin could address (rather than each individual Airwindows plugin). Sounds reasonable?

Thanks.

Related: https://github.com/baconpaul/airwin2rack/issues/74

**Comment by baconpaul** [comment]
So i think we are going to stabilize this week and let the plugin sit for a few weeks before we add the last few big request, of which this is one (and user favorites #81 is the other)

But here's how I would do it

1. Add a new parameter "Output Attenuation" and make sure to set the version to 2 for the AU or whatever
2. Crib over the -cube-as-decibel- formatter from surge so its not just a linear response
3. Add a knob in the footer next to the bypass; make sure it collapses with documentation off to not overwrite airwindows
4. test both automation and so on
5. Maybe add an option to show/hide output attenuator knob

Since my head is in the code but i'm not doing it with this sweep didn't want that to be lost

**Comment by baconpaul** [comment]
Yes it would be automatable
It would be linear in decibels not amplitude basically. 
thanks!

**Comment by baconpaul** [comment]
request came in for input level also.

**Comment by baconpaul** [comment]
![Screenshot 2024-06-10 at 6 19 40 PM](https://github.com/baconpaul/airwin2rack/assets/13387561/372d3439-9791-4add-994a-3af5d0a3cf3f)

Nightly later tonight will have input and output gain controls which range from -inf to +18 db with a reasonable curve for both ui and automation.
